---
import:
  - jquery/jquery.js
  - jquery/jquery-ui.js
  - jquery/jquery.migrate.min.js
  - jquery/jquery.cookie.js
  - jquery/jquery.rightClick.js
  - jquery/jquery.resize.js
  - jquery/jquery.dialogextend.1_0_1.js
  - jquery/jquery.ui.datepicker-ru.js
  - spin.min.js
  - jquery.spin.js
  - core.js
  - events.js
  - core.component.js
  - flex.js
  - flex.apiTable.js
  - flex.tree.js
  - flex.window.js
  - ui.js
  - api.js
  - lightbox/lightbox.js
  - lightbox/css/lightbox.css
  - { path: core.editor, as: directory }
  - { path: mCustomScrollbar, as: directory }